config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :edit, :update] do
    member do
      get :followings
      get :likes
    end
  end
  resources :trainingposts, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :search
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: {maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    validates :introduce, length: { maximum: 255 }
    has_secure_password
    
    mount_uploader :icon_img, ImgUploader
    has_many :trainingposts
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    has_many :favorites
    has_many :favorite_trainingpost, through: :favorites, source: :trainingpost
    
    def follow(other_user)
        unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
        end
    end
    
    def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
    end
    
    def following?(other_user)
        self.followings.include?(other_user)
    end
    
    def like(trainingpost)
        self.favorites.find_or_create_by(trainingpost_id: trainingpost.id)
    end
    
    def unlike(trainingpost)
        favorite = self.favorites.find_by(trainingpost_id: trainingpost.id)
        favorite.destroy if favorite
    end    
    
    def liking?(trainingpost)
        self.favorite_trainingpost.include?(trainingpost)
    end
    
    #連続投稿
    #   def is_continuos_post
    #     continuos_post_at = current_user.trainingposts.last.created_at.to_date #前の投稿の情報を取得する
    #     d = Date.today
    #     yesterday = d - 1
    #     if continuos_post_at == yesterday
    #       current_user.increment(:continuos_count, 1)
    #       current_user.continuos_count.save
    #     elsif continuos_post_at < yesterday
    #       current_user.continuos_count = 1
    #       current_user.continuos_count.save
    #     end
    #   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @trainingposts = @user.trainingposts.order(id: :desc).page(params[:page]).per(5)
    counts(@user)
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーの登録が完了しました！'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録が出来ていません！'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = 'プロフィールを更新しました！'
        redirect_to @user
      else
        flash.now[:danger] = 'プロフィールを更新できていません！'
        render :edit
      end
      
  end
  
  def followings
    @user = User.find(params[:id])
    @followers = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @trainingposts = @user.favorite_trainingpost.order(id: :desc).page(params[:page]).per(5)
    counts(@user)
  end


  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon_img, :introduce)
  end
end

app/views/users/_user.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%=  link_to 'View_profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
            <%= f.label :icon_img, 
                if @user.icon_img?
                    '画像を変更しよう！'
                else
                    '画像を登録しよう！'
                end %>
            <%= f.file_field :icon_img %>
        </div>
        <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :introduce, '自己紹介' %>
            <%= f.text_area :introduce, class: 'form-control' %>
        </div>
        
            <%= f.submit '保存する！', class: 'btn btn-block btn-primary' %>
            
        <% end %>
    </div>
</div>

app/views/users/followings.html.erb
<div class="container">
    <div class="justify-content-center">
        <% if @user.icon_img? %>
            <%= image_tag @user.icon_img.url, class: 'd-block mx-auto', :size => '300x300' %>
        <% end %>
        
        <h3 class="text-center"><%= @user.name %></h3>
        
        <p class="text-center"><%= @user.introduce %></p>
        <%= render 'relationships/follow_button', user: @user %>
        
        
        <p class="text-center"><%= link_to 'プロフィールを編集する', edit_user_path(@user) %></p>
    </div>
    <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user))%>">Microposts <span class="badge badge-secondary"><%= @count_trainingposts %></span></a></li>
        <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%='active' if current_page?(likes_user_path(@user)) %>">Favorites <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'user', users: @followers %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/likes.html.erb
<div class="container">
    <div class="justify-content-center">
        <% if @user.icon_img? %>
            <%= image_tag @user.icon_img.url, class: 'd-block mx-auto', :size => '300x300' %>
        <% end %>
        
        <h3 class="text-center"><%= @user.name %></h3>
        
        <p class="text-center"><%= @user.introduce %></p>
        <div class="mb-3 text-center">
            <%= render 'relationships/follow_button', user: @user %>
        </div>
        <% if current_user == @user %>
            <p class="text-center"><%= link_to 'プロフィールを編集する', edit_user_path(@user) %></p>
        <% end %>
    </div>
    <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item" style="width: 30%;"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user))%>">Microposts <span class="badge badge-secondary"><%= @count_trainingposts %></span></a></li>
        <li class="nav-item" style="width: 30%;"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
        <li class="nav-item" style="width: 30%;"><a href="<%= likes_user_path(@user) %>" class="nav-link <%='active' if current_page?(likes_user_path(@user)) %>">Favorites <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'trainingposts/index', trainingposts: @trainingposts %>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group">
            <%= f.label :icon_img, '画像を登録しよう！' %>
                <!--id "file"で、fileとdivを紐付けクリック時に連動-->
                  <div id="icon_img_field" onClick="$('#icon_file').click()" >
             
                    <!--// 画像があるときは画像を表示する-->
                    <% if @user.icon_img.present? %>
                      <%= image_tag(@user.icon_img.url) %>
                     <% else %>
                    　<i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
                    <% end %>
             
                  </div>
    
            <%= f.file_field :icon_img, class: "image", style: "display: none;", id: "icon_file" %>
        </div>
        <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（もう一度パスワードをもう一度入力してください）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
            <%= f.submit '登録する！', class: 'btn btn-block btn-primary' %>
            
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <% if @user.icon_img? %>
        <%= image_tag @user.icon_img.url %>
    <% end %>
    <p><%= @user.name %></p>
    
    <p><%= @user.introduce %></p>
    <%= render 'relationships/follow_button', user: @user %>
    
    
    <%= link_to 'プロフィールを編集する', edit_user_path(@user) %>
</div>