config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :edit, :update] do
    member do
      get :followings
      get :likes
    end
  end
  resources :trainingposts, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :search
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/trainingpost.rb
class Trainingpost < ApplicationRecord
  belongs_to :user
  validates :title, length: { maximum: 50}
  validates :content, presence: true, length: { maximum: 255 }
  validates :training_part, presence: true
  
  
  mount_uploader :post_img, ImgUploader
  has_many :favorites, dependent: :destroy
  has_many :fovorite_user, through: :fovorites, source: :user
  
  after_create :is_continuos_post
  
  def self.search(search)
    search ? where('content LIKE ? OR training_part LIKE ?', "%#{search}%", "%#{search}%") :all
  end
  
  private
  #連続投稿について記述
  def is_continuos_post
    d = Date.today
    yesterday = d - 1
    tyokuzen_trainingpost = self.user.trainingposts[-2]
    if tyokuzen_trainingpost
      continuos_post_at = tyokuzen_trainingpost.created_at.to_date
      if continuos_post_at == yesterday
        self.user.increment(:continuos_count, 1)
        self.user.save
      elsif continuos_post_at < yesterday
        self.user.continuos_count = 1
        self.user.save
      end
    else
      self.user.continuos_count = 1
      self.user.save
    end
  end
end

app/controllers/trainingposts_controller.rb
class TrainingpostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :training_part_array, only: [:create]
  def index
    @user = User.find(params[:id])
    @trainingposts = @user.trainingposts.order(id: :desc).page(params[:page]).per(5)
  end

  def show
    @trainingpost = Trainingpost.find(params[:id])
  end

  def new
    if logged_in?
      @trainingpost = current_user.trainingposts.build
    end
  end

  def create
    @trainingpost = current_user.trainingposts.build(trainingpost_params)
    if @trainingpost.save
      flash[:success] = '投稿できました！'
      redirect_to @trainingpost
    else
      flash.now[:danger] = '投稿できていません！'
      render :new
    end
  end

  def destroy
    @user = current_user
    @trainingpost = Trainingpost.find(params[:id])
    @trainingpost.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to @user
  end
  
  def search
    @trainingposts = Trainingpost.all.search(params[:search]).order(id: :desc).page(params[:page]).per(5)
  end
  
 
  
  private
  def trainingpost_params
    params.require(:trainingpost).permit(:title, :content, :training_part, :post_img)
  end
  
  def training_part_array
    if params[:trainingpost][:training_part]
      params[:trainingpost][:training_part] = params[:trainingpost][:training_part].join("/")
    end
  end
end

app/views/trainingposts/_index.html.erb
<ul class="list-unstyled">
    <% trainingposts.each do |trainingpost| %>
        <li class="media mb-3">
            <div class="media-body" style="position: relative; padding: .5em .75em; background-color: #f0f0f0; border-radius: 6px; :hover {text-decoration: none;};">
                <%= link_to trainingpost.user.name, user_path(trainingpost.user) %>
                <%= link_to trainingpost_path(id: trainingpost.id) do %>
                <div class="text-dark">
                    <h4><%= trainingpost.title %></h4>
                </div>
                <div class="border-bottom border-muted my-1"></div>
                <div>
                    <p class="text-dark"><%= trainingpost.content %></p>
                </div>
                <div>
                    <p class="text-dark"><%= trainingpost.training_part %>をトレーニングしました！</p>
                </div>
                <div class="border-bottom border-muted my-1"></div>
                 <div>
                    <span class="text-muted">posted at <%= trainingpost.created_at %></span>
                 </div>
                <div class="border-bottom border-muted my-1"></div>
            <% end %>
            <div class="container">
                <div class="row">
                    <%= render 'favorites/like_button', trainingpost: trainingpost %>
                    <div class="col-sm"><%= trainingpost.user.continuos_count %>日連続投稿！</div>
                </div>
            </div>
            </div>
        </li>
    <% end %>
        <%= form_tag(search_trainingposts_path, method: :get) do%>
            <div class="input-group">
              <%= text_field_tag :search, nil, placeholder: 'キーワードを入力してみよう！', class: "form-control size:30" %>
              <span class="input-group-btn">
                <%= submit_tag '検索', class: 'btn btn-secondary' %>
              </span>
            </div>
        <% end %>
    <%= paginate @trainingposts %>
</ul>

app/views/trainingposts/new.html.erb
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @trainingpost, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, placeholder: 'タイトルを入力しよう', class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :content %>
                <%= f.text_area :content, placeholder: '本文を入力しよう', class: 'form-control' %>
            </div>
            <div class="form-group">
                <div class="clo-sm-2">
                    <%= f.label :training_part %>
                </div>
                <div class="col-sm-12 btn-group" data_toggle="button">
                    <% ["全身", "上半身", "下半身", "胸", "背中", "脚", "お腹", "肩", "腕", "お尻", "体幹"].each do |training_part| %>
                    <label class="btn btn-outline-secondary" style="width:50%">
                        <%= f.check_box :training_part, {multiple: true}, training_part, nil %>
                        <%= training_part %>
                    </label>
                    <% end %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :post_img, '写真を投稿しよう' %>
                    <!--id "file"で、fileとdivを紐付けクリック時に連動-->
                  <div id="img_field" onClick="$('#file').click()" >
             
                    <!--// 画像があるときは画像を表示する-->
                    <% if @trainingpost.post_img.present? %>
                      <%= image_tag(@trainingpost.post_img.url) %>
                     <% else %>
                    　<i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
                    <% end %>
             
                  </div>
    
                <%= f.file_field :post_img, class: "image", style: "display: none;", id: "file" %>
            </div>
            <%= f.submit '投稿する！', class: 'btn btn-secondary btn-sm' %>
        <% end %>
    </div>
</div>

app/views/trainingposts/search.html.erb
<div class="container">
    <%= form_tag(search_trainingposts_path, method: :get) do%>
        <div class="input-group">
            <%= text_field_tag :search, nil, placeholder: 'キーワードを入力してみよう！', class: "form-control size:30" %>
            <span class="input-group-btn">
                <%= submit_tag '検索', class: 'btn btn-secondary' %>
            </span>
        </div>
    <% end %>
    <ul class="list-unstyled">
        <% @trainingposts.each do |trainingpost| %>
            <li class="media mb-3">
            <div class="media-body" style="position: relative; padding: .5em .75em; background-color: #f0f0f0; border-radius: 6px; :hover {text-decoration: none;};">
                <%= link_to trainingpost.user.name, user_path(trainingpost.user) %>
                <%= link_to trainingpost_path(id: trainingpost.id) do %>
                    <div class="text-dark">
                        <h4><%= trainingpost.title %></h4>
                    </div>
                    <div class="border-bottom border-muted my-1"></div>
                    <div>
                        <p class="text-dark"><%= trainingpost.content %></p>
                    </div>
                    <div>
                        <p class="text-dark"><%= trainingpost.training_part %>をトレーニングしました！</p>
                    </div>
                    <div class="border-bottom border-muted my-1"></div>
                     <div>
                        <span class="text-muted">posted at <%= trainingpost.created_at %></span>
                     </div>
                    <div class="border-bottom border-muted my-1"></div>
                <% end %>
            <div class="container">
                <div class="row">
                    <%= render 'favorites/like_button', trainingpost: trainingpost %>
                    <div class="col-sm"><%= trainingpost.user.continuos_count %>日連続投稿！</div>
                </div>
            </div>
            </div>
        </li>
        <% end %>
        
        <%= paginate @trainingposts %>
    </ul>
</div>

app/views/trainingposts/show.html.erb
<div class="media mb-3">
    <div class="media-body" style="position: relative; padding: .5em .75em; background-color: #f0f0f0; border-radius: 6px; :hover {text-decoration: none;};">
        <%= link_to @trainingpost.user.name, user_path(@trainingpost.user) %>
            <div class="text-dark">
                <h3><%= @trainingpost.title %></h3>
            </div>
            <div class="border-bottom border-muted my-1"></div>
            <div>
                <h5 class="text-dark"><%= @trainingpost.content %></h5>
            </div>
            <div>
                <p class="text-dark"><%= @trainingpost.training_part %>をトレーニングしました！</p>
            </div>
            <div class="border-bottom border-muted my-1"></div>
            <div>
                <% if @trainingpost.post_img? %>
                    <%= image_tag @trainingpost.post_img.url %>
                <% end %>
            </div>
            <div>
                <span class="text-muted">posted at <%= @trainingpost.created_at %></span>
            </div>
            <div class="border-bottom border-muted my-1"></div>
            <div class="container">
                <div class="row">
                    <%= render 'favorites/like_button', trainingpost: @trainingpost %>
                    <div class="col-sm"><%= @trainingpost.user.continuos_count %>日連続投稿！</div>
                    <% if current_user == @trainingpost.user %>
                        <%= link_to '削除', @trainingpost, method: :delete, data: {confirm: "本当に削除してもいいですか？"}, class: 'btn btn-danger btn-sm' %>
                    <% end %>
                </div>
            </div>
    </div>
</div>